import logo from "../assets/images/logo.png";
export const buyers = {
  data: [
    {
      id: "d1",
      name: "squashApps",
      logo: logo,
      contactPerson: "abiram",
      contactNumber: "452133255",
      phone: "9790440471",
      faxNo: "+65 2125 221",
      address: "107-a,tkr nager, marudhamalai",
      emailId: "abiram@squashapps.com",
      website: "squashapps.com",
      totalOrers: "+255k",
    },
    {
      id: "d2",
      name: "BMW motorad",
      logo: logo,
      contactPerson: "sibiram d",
      contactNumber: "452133+255k",
      phone: "9790440471",
      faxNo: "+65 2125 221",
      address: "107-a,tkr nager, marudhamalai",
      emailId: "abiram@squashapps.com",
      website: "squashapps.com",
      totalOrers: "+255k",
    },
    {
      id: "d3",
      name: "aadu inc",
      logo: logo,
      contactPerson: "sriram",
      contactNumber: "452133+255k",
      phone: "9790440471",
      faxNo: "+65 2125 221",
      address: "107-a,tkr nager, marudhamalai",
      emailId: "abiram@squashapps.com",
      website: "squashapps.com",
      totalOrers: "+255k",
    },
    {
      id: "d4",
      name: "swashApps",
      logo: logo,
      contactPerson: "iram",
      contactNumber: "452133+255k",
      phone: "9790440471",
      faxNo: "+65 2125 221",
      address: "107-a,tkr nager, marudhamalai",
      emailId: "abiram@squashapps.com",
      website: "squashapps.com",
      totalOrers: "+255k",
    },
    {
      id: "d5",
      name: "squashApps",
      logo: logo,
      contactPerson: "abiram",
      contactNumber: "452133+255k",
      phone: "9790440471",
      faxNo: "+65 2125 221",
      address: "107-a,tkr nager, marudhamalai",
      emailId: "abiram@squashapps.com",
      website: "squashapps.com",
      totalOrers: "+255k",
    },
  ],
};
